apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp-dev
resources:
- ../../base
- ../../hooks
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: myapp
configMapGenerator:
- behavior: merge
  literals:
  - APP_COLOR=green
  name: myapp-config
images:
- name: ghcr.io/shubhamkri/argocd-lab-app
  newName: ghcr.io/shubhamkri/agrocd-lab-app
  newTag: sha-2a66bb4
